apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-lpyn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-lpyn
    app.kubernetes.io/part-of: test-app-wxph
  name: test-component-lpyn
  namespace: build-e2e-qbxx-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-lpyn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-lpyn
    spec:
      containers:
      - image: quay.io/susdas/test-images:00ed88c8c404413b9bf263229459693a
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
